# 1. Create a 3x3x3 array with random values 

In [4]:
import numpy as np
randomarray = np.random.random((3,3,3))
print(randomarray)

[[[0.89581751 0.51575464 0.1925681 ]
  [0.12573688 0.02525888 0.56954554]
  [0.55184666 0.35303448 0.59928693]]

 [[0.85166486 0.58122021 0.70819231]
  [0.80505449 0.38681691 0.46781704]
  [0.79817354 0.4984954  0.83034301]]

 [[0.65139322 0.8240203  0.13218641]
  [0.13483436 0.55462818 0.20506564]
  [0.11652076 0.0358306  0.79195541]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [62]:
import numpy as np
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [9]:
import numpy as np
checkerboard=np.ones((3,3))
checkerboard=np.zeros((8,8),dtype=int)
checkerboard[1::2,::2] = 1
checkerboard[::2,1::2] = 1
print(checkerboard)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 4. Normalize a 5x5 random matrix

In [19]:
import numpy as np
x= np.random.random((5,5))
print("Before Normalization: \n",x)
xmax, xmin = x.max(), x.min()
x = (x - xmin)/(xmax - xmin)
print("After Normalization: \n",x)

Before Normalization: 
 [[0.6708014  0.15555528 0.82999781 0.64271786 0.86207996]
 [0.78346358 0.35657511 0.74619811 0.26205616 0.14664046]
 [0.09546977 0.70994065 0.17703478 0.80772454 0.70225495]
 [0.15052111 0.06597842 0.37853013 0.92588427 0.98791258]
 [0.34873098 0.94294118 0.14000427 0.5272509  0.54378444]]
After Normalization: 
 [[0.65603706 0.09716189 0.82871361 0.62557552 0.86351236]
 [0.77823904 0.3152033  0.73781808 0.21268085 0.08749219]
 [0.03198856 0.69849048 0.12046019 0.80455433 0.69015398]
 [0.09170145 0.         0.33901739 0.93271937 1.        ]
 [0.30669496 0.95122059 0.08029407 0.50033126 0.5182648 ]]


# 5.  How to find common values between two arrays?

In [25]:
import numpy as np
x=np.array([12,45,1,76,998,24,-56])
y=np.array([36,12,53,109,76,-56])
"""
for i in x:
    for j in y:
        if i==j:
            print(i)
"""
print(np.intersect1d(x,y))

[-56  12  76]


# 6.How to get the dates of yesterday, today and tomorrow?

In [34]:
import numpy as np
yesterday=np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today=np.datetime64('today', 'D')
print("Today: ",today)
tomorrow=np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2020-07-27
Today:  2020-07-28
Tomorrow:  2020-07-29


# 7. Consider two random array A and B, check if they are equal

In [39]:
import numpy as np
arr1 = np.random.randint(1,10,(3,3))  
print("First array: \n",arr1)
arr2=np.random.randint(1,10,(3,3))
print("Second array: \n",arr2)
np.array_equal(arr1,arr2)

First array: 
 [[4 3 1]
 [6 8 4]
 [5 8 3]]
Second array: 
 [[7 1 4]
 [2 4 8]
 [3 7 1]]


False

# 8.Create random vector of size 10 and replace the maximum value by 0 

In [45]:
import numpy as np
x = np.random.random(10)
print("Original array:")
print(x)
x[x.argmax()]=0
print(x)

Original array:
[0.29865824 0.14282082 0.31144931 0.41925299 0.32545467 0.77060995
 0.23132678 0.06135525 0.82719029 0.41511671]
[0.29865824 0.14282082 0.31144931 0.41925299 0.32545467 0.77060995
 0.23132678 0.06135525 0.         0.41511671]


# 9. How to print all the values of an array?

In [59]:
import numpy as np
my_array = np. arange(15)
print(my_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


# 10.Subtract the mean of each row of a matrix

In [60]:
import numpy as np
print("Original matrix:\n")
X=np.random.rand(5, 10)
print(X)
print("\nSubtract the mean of each row of the said matrix:\n")
Y=X-X.mean(axis=1, keepdims=True)
print(Y)

Original matrix:

[[0.20626556 0.21156291 0.07408743 0.27876698 0.50361344 0.67961992
  0.20137583 0.48174186 0.03944471 0.61777579]
 [0.54552754 0.85533505 0.27439871 0.12691313 0.90797179 0.83218108
  0.97005176 0.92167374 0.86125169 0.56234314]
 [0.20489328 0.40043258 0.8041871  0.41135886 0.13909547 0.35088346
  0.62314836 0.32186342 0.10844966 0.38325537]
 [0.61783912 0.67615645 0.13088025 0.52138335 0.12502247 0.72333912
  0.05723508 0.44391828 0.42457408 0.33347352]
 [0.9391162  0.82450634 0.5464277  0.80476123 0.23615683 0.53820135
  0.92389257 0.1559545  0.92007441 0.03315317]]

Subtract the mean of each row of the said matrix:

[[-0.12315989 -0.11786253 -0.25533801 -0.05065846  0.174188    0.35019448
  -0.12804961  0.15231642 -0.28998073  0.28835035]
 [-0.14023722  0.16957028 -0.41136605 -0.55885163  0.22220703  0.14641632
   0.28428699  0.23590898  0.17548692 -0.12342162]
 [-0.16986348  0.02567582  0.42943035  0.0366021  -0.23566128 -0.0238733
   0.24839161 -0.05289334 -0.26

# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [67]:
X=np.ones(10)
Y=np.random.randint(0,len(X),20)
X+=np.bincount(Y,minlength=len(X))
print(X)

[2. 4. 3. 5. 2. 2. 3. 3. 2. 4.]


# 12.How to get the diagonal of a dot product?

In [69]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([2.53249707, 0.24791289, 1.8735232 , 1.76624494, 1.81224459])

# 13.How to find the most frequent value in an array?

In [73]:
X=np.random.randint(0,10,25)
print(X)
print(np.bincount(X).argmax())

[4 5 9 8 6 0 0 5 9 1 0 6 5 8 3 4 8 7 7 1 2 7 3 5 9]
5


# 14.How to get the n largest values of an array

In [83]:
X=np.arange(50)
np.random.shuffle(X)
n=7
print(X[np.argpartition(-X,n)[:n]])

[49 44 48 45 46 47 43]


# 15.How to create a record array from a regular array?

In [86]:
Z=np.array([("Hello", 2.5, 3),("World", 3.6, 2)])
R=np.core.records.fromarrays(Z.T,names='col1, col2, col3',formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]
